=== bcyj/android_tools_leeco_msm8996/data/mobileap_v2/server/src/mobileap_cfg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2011-2013 Qualcomm Technologies, Inc.  All Rights Reserved. Qualcomm Technologies Proprietary and Confidential. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="system">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MobileAPDbg"/>
				<xs:element ref="MobileAPCfg"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EnableIPV4">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableIPV6">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Module">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="ar6000"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="WlanMode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="AP"/>
				<xs:enumeration value="AP-AP"/>
				<xs:enumeration value="AP-STA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
        <xs:element name="MobileAPSTABridgeEnable">
                <xs:simpleType>
                        <xs:restriction base="xs:byte">
                                <xs:enumeration value="1"/>
                                <xs:enumeration value="0"/>
                        </xs:restriction>
                </xs:simpleType>
        </xs:element>
	<xs:element name="AccessProfile">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="FULL"/>
				<xs:enumeration value="INTERNETONLY"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DHCPCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="StartIP"/>
				<xs:element ref="EndIP"/>
				<xs:element ref="LeaseTime"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
		<xs:element name="DHCPReservationRecords">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ClientMACAddr"/>
				<xs:element ref="ClientReservedIP"/>
				<xs:element ref="ClientName"/>
				<xs:element ref="Reservation"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="STAModeConnType">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SupplicantCfg">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="/etc/wpa_supplicant.conf"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="StartIP">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="192.168.1.20"/>
				<xs:enumeration value="192.168.2.20"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LeaseTime">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="12h"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EndIP">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="192.168.1.40"/>
				<xs:enumeration value="192.168.2.40"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
		<xs:element name="ClientMACAddr">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="aa:bb:cc:dd:11:22"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ClientReservedIP">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="192.168.1.8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ClientName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="hostname"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Reservation">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GuestAPCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="HostAPDCfg"/>
				<xs:element ref="HostAPDEntropy"/>
				<xs:element ref="AccessProfile"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StationModeCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SupplicantCfg"/>
				<xs:element ref="STAModeConnType"/>
				<xs:element ref="StaticIPAddr"/>
				<xs:element ref="StaticConfigDNSAddr"/>
				<xs:element ref="StaticConfigGWAddr"/>
				<xs:element ref="StaticConfigNetMask"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="V4_UMTS_PROFILE_INDEX">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="V6_UMTS_PROFILE_INDEX">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TECH">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="ANY"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SubNetMask">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="255.255.255.0"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="MobileAPWanCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="AutoConnect"/>
				<xs:element ref="Roaming"/>
				<xs:element ref="EriConfig"/>
				<xs:element ref="TECH"/>
				<xs:element ref="V4_UMTS_PROFILE_INDEX"/>
				<xs:element ref="V4_CDMA_PROFILE_INDEX"/>
				<xs:element ref="V6_UMTS_PROFILE_INDEX"/>
				<xs:element ref="V6_CDMA_PROFILE_INDEX"/>
				<xs:element ref="DefaultSIPServerConfigType"/>
				<xs:element ref="DefaultSIPServerConfig"/>
				<xs:element ref="PrefixDelegation"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MobileAPNatCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="NATType"/>
				<xs:element ref="FirewallEnabled"/>
				<xs:element ref="FirewallPktsAllowed"/>
				<xs:element ref="Firewall"/>
				<xs:element ref="PortFwding"/>
				<xs:element ref="NatEntryTimeout"/>
				<xs:element ref="DmzIP"/>
				<xs:element ref="EnableIPSECVpnPassthrough"/>
				<xs:element ref="EnablePPTPVpnPassthrough"/>
				<xs:element ref="EnableL2TPVpnPassthrough"/>
				<xs:element ref="EnableWebserverWWANAccess"/>
				<xs:element ref="ALGCfg"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MobileAPLanCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Module"/>
				<xs:element ref="EnableIPV4"/>
				<xs:element ref="EnableIPV6"/>
				<xs:element ref="WlanMode"/>
				<xs:element ref="HostAPDCfg"/>
				<xs:element ref="HostAPDEntropy"/>
				<xs:element ref="STAModeHostAPDCfg"/>
				<xs:element ref="APIPAddr"/>
				<xs:element ref="SubNetMask"/>
				<xs:element ref="EnableDHCPServer"/>
				<xs:element ref="DHCPCfg"/>
				<xs:element ref="DHCPReservationRecords"/>
				<xs:element ref="USBCfg"/>
				<xs:element ref="SSID2Cfg"/>
				<xs:element ref="SSID3Cfg"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MobileAPCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MobileAPNatCfg"/>
				<xs:element ref="MobileAPLanCfg"/>
				<xs:element ref="MobileAPWanCfg"/>
				<xs:element ref="Cradle"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MobileAPSrvcCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="UPnP"/>
				<xs:element ref="DLNA"/>
				<xs:element ref="MDNS"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
        <xs:element name="MobileAPSTABridgeCfg">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="MobileAPSTABridgeEnable"/>
                        </xs:sequence>
                </xs:complexType>
        </xs:element>
	<xs:element name="Roaming">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EriConfig">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="/etc/mobileap_eri_config.bin"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DefaultSIPServerConfigType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="FQDN"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DefaultSIPServerConfig">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="abcd.com"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PrefixDelegation">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PortFwdingProtocol">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="17"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PortFwdingPrivatePort">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="5500"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PortFwdingPrivateIP">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="192.168.1.8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PortFwdingGlobalPort">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="5500"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PortFwding">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PortFwdingPrivateIP"/>
				<xs:element ref="PortFwdingPrivatePort"/>
				<xs:element ref="PortFwdingGlobalPort"/>
				<xs:element ref="PortFwdingProtocol"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="NatEntryGenericTimeout">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="200"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NatEntryICMPTimeout">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="30"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NatEntryTCPEstablishedTimeout">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="3600"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NatEntryUDPTimeout">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="60"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="HostAPDCfg">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="/etc/hostapd.conf"/>
				<xs:enumeration value="/etc/hostapd-wlan1.conf"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="HostAPDEntropy">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="/etc/entropy_file"/>
				<xs:enumeration value="/etc/entropy_file1"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="STAModeHostAPDCfg">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="/etc/sta_mode_hostapd.conf"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FirewallProtocol">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="6"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FirewallEndPort">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="23"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FirewallStartPort">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="23"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NATType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="SYM"/>
				<xs:enumeration value="PRC"/>
				<xs:enumeration value="FC"/>
				<xs:enumeration value="ARC"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FirewallEnabled">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FirewallPktsAllowed">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Firewall">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FirewallStartPort"/>
				<xs:element ref="FirewallEndPort"/>
				<xs:element ref="FirewallProtocol"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EnablePPTPVpnPassthrough">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableL2TPVpnPassthrough">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableIPSECVpnPassthrough">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableWebserverWWANAccess">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ALGCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="EnableRTSPAlg"/>
				<xs:element ref="EnableSIPAlg"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EnableRTSPAlg">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableSIPAlg">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableHostAPD">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableDHCPServer">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DmzIP">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0.0.0.0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="V4_CDMA_PROFILE_INDEX">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="V6_CDMA_PROFILE_INDEX">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="AutoConnect">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="APIPAddr">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="192.168.1.1"/>
				<xs:enumeration value="192.168.2.1"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="StaticIPAddr">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0.0.0.0"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="StaticConfigDNSAddr">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0.0.0.0"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="StaticConfigGWAddr">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0.0.0.0"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="StaticConfigNetMask">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0.0.0.0"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="UPnP">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DLNA">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="MDNS">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="MobileAPEnableAtBootup">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="WLANEnableAtBootup">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="MobileAPDbg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SupplicantCmdAppend"/>
				<xs:element ref="HostapdCmdAppend"/>
				<xs:element ref="GuestHostapdCmdAppend"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SupplicantCmdAppend">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="HostapdCmdAppend">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GuestHostapdCmdAppend">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Cradle">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CradleMode"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CradleMode">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="3"/>
				<xs:enumeration value="4"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== bcyj/android_tools_leeco_msm8996/data/mobileap_v2/server/src/mobileap_cfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2011-2013 Qualcomm Technologies, Inc.  All Rights Reserved. Qualcomm Technologies Proprietary and Confidential. -->
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mobileap_cfg.xsd">
	<MobileAPCfg>
		<MobileAPNatCfg>
			<Firewall>/etc/mobileap_firewall.xml</Firewall>
			<NatEntryGenericTimeout>200</NatEntryGenericTimeout>
			<NatEntryICMPTimeout>30</NatEntryICMPTimeout>
			<NatEntryTCPEstablishedTimeout>3600</NatEntryTCPEstablishedTimeout>
			<NatEntryUDPTimeout>60</NatEntryUDPTimeout>
			<DmzIP>0.0.0.0</DmzIP>
			<EnableIPSECVpnPassthrough>1</EnableIPSECVpnPassthrough>
			<EnablePPTPVpnPassthrough>1</EnablePPTPVpnPassthrough>
			<EnableL2TPVpnPassthrough>1</EnableL2TPVpnPassthrough>
			<EnableWebserverWWANAccess>0</EnableWebserverWWANAccess>
			<ALGCfg>
				<EnableRTSPAlg>0</EnableRTSPAlg>
				<EnableSIPAlg>1</EnableSIPAlg>
			</ALGCfg>
		</MobileAPNatCfg>
		<MobileAPLanCfg>
			<Module>qca6174</Module>
			<EnableIPV4>1</EnableIPV4>
			<EnableIPV6>1</EnableIPV6>
			<WlanMode>AP</WlanMode>
			<MobileAPSTABridgeEnable>0</MobileAPSTABridgeEnable>
			<HostAPDCfg>/etc/hostapd.conf</HostAPDCfg>
                        <HostAPDEntropy>/etc/entropy_file</HostAPDEntropy>
			<STAModeHostAPDCfg>/etc/sta_mode_hostapd.conf</STAModeHostAPDCfg>
			<APIPAddr>192.168.225.1</APIPAddr>
			<SubNetMask>255.255.255.0</SubNetMask>
			<EnableDHCPServer>1</EnableDHCPServer>
			<DHCPCfg>
				<StartIP>192.168.225.20</StartIP>
				<EndIP>192.168.225.60</EndIP>
				<LeaseTime>43200</LeaseTime>
			</DHCPCfg>
			<GuestAPCfg>
				<HostAPDCfg>/etc/hostapd-wlan1.conf</HostAPDCfg>
                                <HostAPDEntropy>/etc/entropy_file1</HostAPDEntropy>
				<AccessProfile>INTERNETONLY</AccessProfile>
			</GuestAPCfg>
			<StationModeCfg>
				<SupplicantCfg>/etc/wpa_supplicant.conf</SupplicantCfg>
				<STAModeConnType>1</STAModeConnType>
				<StaticIPAddr>0</StaticIPAddr>
				<StaticConfigDNSAddr>0</StaticConfigDNSAddr>
				<StaticConfigGWAddr>0</StaticConfigGWAddr>
				<StaticConfigNetMask>0</StaticConfigNetMask>
			</StationModeCfg>
		</MobileAPLanCfg>
		<MobileAPWanCfg>
			<AutoConnect>0</AutoConnect>
			<Roaming>0</Roaming>
			<EriConfig>/etc/mobileap_eri_config.bin</EriConfig>
			<TECH>ANY</TECH>
			<V4_UMTS_PROFILE_INDEX>0</V4_UMTS_PROFILE_INDEX>
			<V4_CDMA_PROFILE_INDEX>0</V4_CDMA_PROFILE_INDEX>
			<V6_UMTS_PROFILE_INDEX>0</V6_UMTS_PROFILE_INDEX>
			<V6_CDMA_PROFILE_INDEX>0</V6_CDMA_PROFILE_INDEX>
			<DefaultSIPServerConfigType>FQDN</DefaultSIPServerConfigType>
			<DefaultSIPServerConfig>abcd.com</DefaultSIPServerConfig>
			<PrefixDelegation>0</PrefixDelegation>
		</MobileAPWanCfg>
		<MobileAPSrvcCfg>
				<UPnP>0</UPnP>
				<DLNA>0</DLNA>
				<MDNS>0</MDNS>
		</MobileAPSrvcCfg>
		<MobileAPBootUpCfg>
	    	<MobileAPEnableAtBootup>0</MobileAPEnableAtBootup>
	    	<WLANEnableAtBootup>0</WLANEnableAtBootup>
	    </MobileAPBootUpCfg>
		<Cradle>
			<CradleMode>0</CradleMode>
		</Cradle>
	</MobileAPCfg>
</system>
